# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = ["dm-snapshot"];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ca684f38-074b-4243-a48f-01e1793ea929";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E2A6-264C";
    fsType = "vfat";
  };

  fileSystems."/backups" = {
    device = "/dev/disk/by-uuid/4497f585-a5a7-40a3-bd95-7e8efe60be5e";
    fsType = "ext4";
    options = ["nofail"];
  };

  swapDevices = [
    {
      device = "/swapfile";
      size = (1024 * 16) + (1024 * 2);
    }
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  hardware.cpu.intel.updateMicrocode = true;
}
