# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  # enable hibernation
  boot.resumeDevice = "/dev/disk/by-uuid/98cc9159-2cb8-4756-8971-b97c04638808";
  boot.kernelParams = ["resume_offset=2630912"];
  security.protectKernelImage = false;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/98cc9159-2cb8-4756-8971-b97c04638808";
    fsType = "btrfs";
    options = ["subvol=root" "compress=zstd" "noatime"];
  };

  boot.initrd.luks.devices."nixenc".device = "/dev/disk/by-uuid/49f0d8b3-5171-4738-8204-c109cef2c3b3";
  boot.initrd.luks.devices."nixenc".allowDiscards = true;

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/98cc9159-2cb8-4756-8971-b97c04638808";
    fsType = "btrfs";
    options = ["subvol=home" "compress=zstd" "noatime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3BA0-A66B";
    fsType = "vfat";
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/98cc9159-2cb8-4756-8971-b97c04638808";
    fsType = "btrfs";
    options = ["subvol=nix" "compress=zstd" "noatime"];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/98cc9159-2cb8-4756-8971-b97c04638808";
    fsType = "btrfs";
    options = ["subvol=swap" "noatime"];
  };

  swapDevices = [{device = "/swap/swapfile";}];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
