{
  # jeffas = {
  #   primary = true;
  #   color = "light cyan";
  #   primaryCollection = "personal";
  #   address = "andrew@jeffas.net";
  #   url = "https://dav.home.jeffas.net/";
  #   userName = "andrew";
  # };
  nextcloud = {
    primary = true;
    color = "light green";
    primaryCollection = "personal";
    address = "nextcloud";
    url = "https://cloud.jeffas.net/";
    userName = "Andrew";
    # contact_birthdays is auto-generated by Nextcloud from contacts and is
    # read-only over CalDAV, so uploads to it always 403.
    # Remote slug is personal-1 (personal was deleted after it turned out to
    # be VEVENT-only), but the local dir is named personal; map them together.
    # Entry format is [pair name, a(remote) id, b(local) id].
    vdirsyncerCollections = ["joint" ["personal" "personal-1" "personal"]];
  };
}
