{
 "title": "A dashboard for laptop batteries",
 "description": "Power information for laptops\nAll you need is node_exporter running.\nPower and battery stats are exposed by the kernel.\n\nTested only on laptops running Linux.",
 "tags": [
  "prometheus",
  "nodeexpoter",
  "laptop"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "batt",
    "label": "Battery",
    "query": "label_values(node_power_supply_present,power_supply)"
   }
  ]
 },
 "panels": [
  {
   "title": "Battery Charge",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_power_supply_capacity{instance=~\"$node\"}",
     "legendFormat": "Battery percentage"
    }
   ]
  },
  {
   "title": "Battery status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_power_supply_info{instance=~\"$node\", type=\"Battery\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_power_supply_voltage_volt{instance=~\"$node\"}",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "Cycle Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_power_supply_cyclecount{instance=~\"$node\"}",
     "legendFormat": "Battery Cycle count"
    }
   ]
  },
  {
   "title": "Battery Degradation Percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_power_supply_energy_full{instance=~\"$node\"} * 100) / node_power_supply_energy_full_design{instance=~\"$node\"})",
     "legendFormat": "Degradation %{$node}"
    }
   ]
  },
  {
   "title": "Battery Charge over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_power_supply_capacity{instance=~\"$node\"}",
     "legendFormat": "Battery Charge"
    }
   ]
  },
  {
   "title": "Voltage over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "volt", "label": "Voltage" }
   ],
   "targets": [
    {
     "expr": "node_power_supply_voltage_volt{instance=~\"$node\"}",
     "legendFormat": "real time voltage"
    },
    {
     "expr": "node_power_supply_voltage_min_design{instance=~\"$node\"}",
     "legendFormat": "Minimum Voltage"
    }
   ]
  },
  {
   "title": "Measured Batteries",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "node_power_supply_info{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Remaining Energy Watt hour over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "watth", "label": "Watt per hour" }
   ],
   "targets": [
    {
     "expr": "node_power_supply_energy_watthour{instance=\"$node\"}",
     "legendFormat": "Energy Watt hour"
    }
   ]
  }
 ]
}