{
 "title": "Dnsmasq",
 "description": "Display data scraped from Prometheus and dnsmasq_exporter.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(dnsmasq_cachesize,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(dnsmasq_cachesize{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CacheSize",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnsmasq_cachesize{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnsmasq_leases{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnsmasq_auth{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ScrapeTime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "increase(dnsmasq_evictions{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "evictions"
    },
    {
     "expr": "increase(dnsmasq_hits{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "hits"
    },
    {
     "expr": "increase(dnsmasq_insertions{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "insertions"
    },
    {
     "expr": "increase(dnsmasq_misses{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "DNS upstream requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "increase(dnsmasq_servers_queries{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{server}}"
    },
    {
     "expr": "increase(dnsmasq_servers_queries_failed{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{server}} - Failed"
    }
   ]
  }
 ]
}