authentication_backend:
  file:
    path: "/var/lib/authelia-home/users.yaml"

storage:
  postgres:
    address: "unix:///var/run/postgresql"
    database: "authelia-home"
    username: "authelia-home"
    password: ""

session:
  secret: "todotestingsecret"
  redis:
    host: "/run/redis-authelia/redis.sock"
  cookies:
  - domain: "home.jeffas.net"
    authelia_url: "https://authelia.home.jeffas.net"

notifier:
  filesystem:
    filename: "/var/lib/authelia-home/notifications.txt"

identity_providers:
  oidc:
    clients:
      - client_id: immich
        client_secret: '{{ secret "/etc/authelia/immichOidcClientSecret" }}'
        authorization_policy: one_factor
        redirect_uris:
          - https://immich.home.jeffas.net/auth/login
          - https://immich.home.jeffas.net/user-settings
          - app.immich:///oauth-callback
        scopes:
          - openid
          - profile
          - email
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: client_secret_post

access_control:
  rules:
  - domain: "webdav.home.jeffas.net"
    policy: one_factor
    subject: "group:andrew-files"
    resources:
      - "^/andrew(/.*)?$"
  - domain: "webdav.home.jeffas.net"
    policy: one_factor
    subject: "group:charlene-files"
    resources:
      - "^/charlene(/.*)?$"
  - domain: "webdav.home.jeffas.net"
    policy: one_factor
    subject: "group:family"
    resources:
      - "^/family(/.*)?$"
  - domain: "webdav.home.jeffas.net"
    policy: deny
  - domain:
    - "*.home.jeffas.net"
    policy: "one_factor"
