name: "CI"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v2

    - run: nix build .#nixosConfigurations.xps15.config.system.build.toplevel
