name: Update flake lock

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v12
      with:
        name: nix-home
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build current config
      id: current
      run: |
        path=$(nix build .#nixosConfigurations.xps-15.config.system.build.toplevel --json | jq -r '.[0].outputs.out')
        echo "path=$path" >> $GITHUB_OUTPUT

    - name: Update flake.lock
      uses: DeterminateSystems/update-flake-lock@v16
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build next config
      id: next
      run: |
        path=$(nix build .#nixosConfigurations.xps-15.config.system.build.toplevel --json | jq -r '.[0].outputs.out')
        echo "path=$path" >> $GITHUB_OUTPUT

    - name: Diff closures
      run: |
        nix store diff-closures ${{ steps.current.outputs.path }} ${{ steps.next.outputs.path }}
